### ISSUE TITLE
zip doesn't work

### ISSUE THREAD

**Issue by Danilwsk** [GamerMJay2008/BetterGameMode#2]
I'm trying to unpack the zip plugin into the planning folder with, the server sees it writing /gm1 nothing happens, although the plugin is installed, please fix it

**Comment by Danilwsk** [comment]
Исправьте пожалуйста

**Comment by Danilwsk** [comment]
please fix it

**Comment by GamerMJay** [comment]
i know i fixing

**Comment by GamerMJay** [comment]
Hey, the bugs are all fixed and there is now a config, thank you for the bug report and for the suggestion, best regards GamerMJay
