### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by Danilwsk** [GamerMJay2008/BetterGameMode#3]
I think it would be good if you added a permission to issue gm to this plugin other players

**Comment by GamerMJay** [comment]
you can also give permission to a player

**Comment by Danilwsk** [comment]
that is, I can write /gm1 Steve , and his gm will turn on?

**Comment by GamerMJay** [comment]
if you give him permission gm1.use he can do it himself but I can also add /gm1 to Steve

**Comment by Danilwsk** [comment]
Yes please make such a permit so that I can issue gm

**Comment by GamerMJay** [comment]
Okay

**Comment by GamerMJay** [comment]
If you want to see spoilers for the plugin you can join my discord https://discord.com/invite/RuF5gxRNfQ

**Comment by Danilwsk** [comment]
ok I'll download the discord now

**Comment by Danilwsk** [comment]
and do you make it possible to change the message when you give someone a gm

**Comment by GamerMJay** [comment]
Yes 👍

**Comment by Danilwsk** [comment]
I'm sorry, of course, but I would really like a plugin for god, that is, immortality

**Comment by Danilwsk** [comment]
When will it be possible to add such a plugin?

**Comment by GamerMJay** [comment]
Godmode?

**Comment by Danilwsk** [comment]
Yes

**Comment by GamerMJay** [comment]
![BetterGodMod](https://user-images.githubusercontent.com/66413999/151601843-c1e1820a-fd01-40a6-bdb3-45d00e413b73.png)

**Comment by GamerMJay** [comment]
:)

**Comment by Danilwsk** [comment]
Thanks)

**Comment by GamerMJay** [comment]
No problem :D

**Comment by Danilwsk** [comment]
Listen, I put the phar file in plugins, went to the server, registered /gm and it crashed

**Comment by Danilwsk** [comment]
tthatsoalsoalsoalsoalso Also inalso youalso howledalso you canalso departurealso crashedalso crashedalso crashedalso crashed also flew toalso flew toalso flew out whenalso flew outalso crashed when prescribed /gm1 Steve

**Comment by GamerMJay** [comment]
/gm 1 Steve is not available yet, will probably be in the next update

**Comment by GamerMJay** [comment]
have you FormAPI?

**Comment by Danilwsk** [comment]
FormApi нету ,можете скинуть суда FormApi?

**Comment by Danilwsk** [comment]
There is no Form Api, can you throw off the FormAPI vessels?

**Comment by Danilwsk** [comment]
vessels*

**Comment by Danilwsk** [comment]
send the link to FormAPI please

**Comment by GamerMJay** [comment]
https://www.mediafire.com/file/0hxsyvfy0jemvvp/FormAPI_v1.3.0.phar/file

**Comment by Danilwsk** [comment]
it turned out, thanks)

**Comment by Danilwsk** [comment]
I'm looking forward to the next update)

**Comment by Danilwsk** [comment]
by the way, can you add permission for the spectator mode? I just think not a big donation privilege should not use the spectator mode.

**Comment by Danilwsk** [comment]
Or the permission won't help there if you can enter the spectator mode with the /gm UI. Then it turns out you need permission to use the /gm UI??

**Comment by Danilwsk** [comment]
Listen, you can put permission on this plugin to give food to the player. And permission to use it , help me , otherwise I can 't ( https://www.mediafire.com/file/nzy599h05zu5h31/SimpleHeal-5a9eae2b49f0967d7bc467586fe5cff63bdd91a8.zip/file

**Comment by GamerMJay** [comment]
Hey @Danilwsk , BetterGameMode has V4 now please install it to run /gm1 steve. I apologize that it took about 3 months, I'm very busy with school at the moment. I hope you enjoy BetterGameMode V4. Best wishes @GamerMJay
